### ISSUE TITLE
Align on either `npm` or `pnpm` for package manager

### ISSUE THREAD

**Issue by trevor-scheer** [apollo-server-integrations/apollo-server-integration-google-cloud-functions#40]
Both lockfiles exist in this repo and it seems to cause issues with renovate (it's not updating the `pnpm-lock.yaml` file correctly. @ernestoresende did you have a preference here?

**Comment by ernestoresende** [comment]
No preference per say, but I'm guessing the lockfile under `/example` exists because the project isn't setup as a monorepo with a workspaces, so it's being considered a separate project.

We could settle on either, and use the package manager workspace feature to have a single lockfile on the root of the project.
